### ISSUE TITLE
VS Code Extension not starting - missing enabledApiProposal?

### ISSUE THREAD

**Issue by kellergoech** [opral/inlang-sherlock#47]
Hello I just installed the sherlock VS Code Extension on the actual OSS Code Version and got following Error:

> Extension 'inlang.vs-code-extension' CANNOT use API proposal: extensionRuntime.
> Its package.json#enabledApiProposals-property declares: \[\] but NOT extensionRuntime.
> The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api inlang.vs-code-extension

from reasearching I found out that this means it uses an Api which is from older Version or one which is not release for productive use in OSS?

![image](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/b3960c04-e2a1-4af4-8824-d6b46dd2c6f3/0d24a9e7-167b-4f76-b6fd-11871bbd6df2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iMzk2MGMwNC1lMmExLTRhZjQtODgyNC1kNmI0NmRkMmM2ZjMvMGQyNGE5ZTctMTY3Yi00Zjc2LWI2ZmQtMTE4NzFiYmQ2ZGYyIiwiaWF0IjoxNzE2Mzc5NTkzLCJleHAiOjMzMjg2OTM5NTkzfQ.R6vJOIo4WjDnkOooPj2BxkZ1o9IF5aKB2hBVqwX4734)

**Comment by samuelstroschein** [comment]
@felix.haeberle is on vacation this week. a reply/fix will follow next week

**Comment by felixhaeberle** [comment]
@kellergoech does it work after you restart vscode?

**Comment by felixhaeberle** [comment]
closing because of stale & can't reproduce.

**Comment by kellergoech** [comment]
Sure I tried to restart several times, and also reinstalled the Plugin.
I use Version 1.89.1 of Vscode

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-16T09:26:03.059Z
Electron: 28.3.3
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.6.32-1-MANJARO

Other Plugins (Dokcer, Continue, Svelte ) all work.

**Comment by felixhaeberle** [comment]
Can you share your `project.inlang/settings.json`?

**Comment by felixhaeberle** [comment]
@kellergoech ping:) I still can't reproduce this at my side, so we need a bit more input from your side. <br><br>Can you share your `project.inlang/settings.json`?<br><br>If there is no further answer we conclude this bug to be not present any longer.

**Comment by KraXen72** [comment]
i'm having the same issue.
fedora 40 kde plasma 6.1
```
{
  "$schema": "https://inlang.com/schema/project-settings",
  "sourceLanguageTag": "en",
  "languageTags": [
    "en",
    "sk"
  ],
  "modules": [
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
	"https://cdn.jsdelivr.net/gh/KraXen72/inlang-t-function-jsx-hybrid-matcher/dist/index.js",
	"https://cdn.jsdelivr.net/npm/@inlang/plugin-json@latest/dist/index.js"
  ],
  "plugin.inlang.json": {
    "pathPattern": "./src/i18n_messages/{languageTag}.json",
    "variableReferencePattern": [
      "%{",
      "}"
    ]
  },
  "plugin.minibits.inlangmatcher": {
    "preferredTfuncName": "translate",
    "recognizedTfuncNames": [
      "translate"
    ]
  }
}
```

**Comment by 0-don** [comment]
same issue here aswell

```json
{
  "$schema": "https://inlang.com/schema/project-settings",
  "sourceLanguageTag": "de",
  "languageTags": ["de", "en", "ru"],
  "modules": [
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-next-intl@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js"
  ],
  "plugin.inlang.nextIntl": {
    "pathPattern": "./public/locales/{languageTag}.json"
  }
}
```

**Comment by felixhaeberle** [comment]
hey, I will investigate this issue tomorrow.

**Comment by 0-don** [comment]
@felixhaeberle No, I am using Arch Linux. I tried running git init or creating a fresh project, but it didn't work there as well.

**Comment by felixhaeberle** [comment]
@0-don Alright, does previous versions work, so can you potentially test with for example 1.45.2 ? You can install another version of the extension by right clicking the list item in the marketplace search.

**Comment by 0-don** [comment]
@felixhaeberle older versions say this

```bash
Failed to load project "/home/don/row/project.inlang": Error: ENOENT: no such file or directory, mkdir '/home/don/MEGA/Projects/scrow/project.inlang/cache/modules
```

**Comment by 0-don** [comment]
@felixhaeberle this is the broken version `1.45.0` works fine
![image](https://github.com/opral/inlang-sherlock/assets/70039285/ef2839b0-f7a9-49c1-b078-dd2e197e37aa)

**Comment by felixhaeberle** [comment]
hey, fix is underway! 🎉<br>[https://github.com/opral/monorepo/pull/2961](https://github.com/opral/monorepo/pull/2961)

**Comment by felixhaeberle** [comment]
Hey there, the fix is released – please update the extension to 1.47.0 (latest) to see this fixed.

**Comment by Sapd** [comment]
Got the same problem, both with 1.45.0 and the latest version 1.48.3
On the latest vscode on Mac

```
Extension 'inlang.vs-code-extension' CANNOT use API proposal: extensionRuntime. Its package.json#enabledApiProposals-property declares: [] but NOT extensionRuntime. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api inlang.vs-code-extension
```

**Comment by fzn0x** [comment]
This issue stills happening , extensions enabled but cannot read the inlang project settings and nothing happened

**Comment by fzn0x** [comment]
https://github.com/user-attachments/assets/4f8bf559-d49b-4bf5-a905-e62dc21cdc56

cc @felixhaeberle @samuelstroschein

**Comment by samuelstroschein** [comment]
@fzn0x we can't reproduce the issue. a PR that fixes the issue is welcome

**Comment by hamstag** [comment]
It's worked when git init

**Comment by samuelstroschein** [comment]
oh wow @felix.haeberle it's when no repo exists. this is fixed in the inlang sdk v2 and thus sherlock v2. release approx q1 2025

**Comment by felixhaeberle** [comment]
I knew that it crashes somewhere inside iso-git and that its not Sherlock related, but thanks for providing an easy solution: don't use it without a git repo (so far) or do git init. <br><br>We will further track this issue and I'l close it as we will release inlang sdk v2 with sherlock v2 somewhere around Q1 2025 as @samuel.stroschein said.

**Comment by samuelstroschein** [comment]
Closing as "run `git init` for sherlock v1 and in Q1 2025 sherlock v2 doesn't depend on git anymore anyways"

**Comment by coldino** [comment]
Just noting that I got this issue when creating a new SvelteKit project and just ticking the Paraglide option, then following the recommendation to install this extension. Git init did fix it, but I spent some time tracking down the error before that point :(

Using 1.48.3, but it sounds like the version isn't the issue.

**Comment by samuelstroschein** [comment]
@coldino i feel you :( the error message is so cryptic that it took 6 months to figure out what's wrong. 

the codebase of sherlock 1 is very outdated, we don't want to touch it anymore to focus on the new codebase in `lix-integration`. in `lix-integration`, sherlock doesn't depend on git anymore

**Comment by phenomen** [comment]
I had the same issue on Tauri + SvelteKit + Paraglide. `git init` fixed it for me.

**Comment by felixhaeberle** [comment]
## For people stumbling on this issue: Try `git init` (initialize your git repository).
If this doesn't work, please open a new issue: https://github.com/opral/inlang-sherlock/issues/new/choose
